// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23AGbp4vVXaRElq8Kn3t0J9fOZPN183g',
    appId: '1:875378909038:web:9ce820e99f777d56b16b7f',
    messagingSenderId: '875378909038',
    projectId: 'fsm-mobile-app-6a2d9',
    authDomain: 'fsm-mobile-app-6a2d9.firebaseapp.com',
    storageBucket: 'fsm-mobile-app-6a2d9.appspot.com',
    measurementId: 'G-EF40N5ETCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4ZIOhzWi7u9BRox4KDsLNIpQ6TB05rw',
    appId: '1:875378909038:android:c63d762adce6a923b16b7f',
    messagingSenderId: '875378909038',
    projectId: 'fsm-mobile-app-6a2d9',
    storageBucket: 'fsm-mobile-app-6a2d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-eetwdaLRqIEtoTxpOthSr6aS7u4BZkI',
    appId: '1:875378909038:ios:5ac2e614a4ec8182b16b7f',
    messagingSenderId: '875378909038',
    projectId: 'fsm-mobile-app-6a2d9',
    storageBucket: 'fsm-mobile-app-6a2d9.appspot.com',
    iosBundleId: 'com.example.fsmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-eetwdaLRqIEtoTxpOthSr6aS7u4BZkI',
    appId: '1:875378909038:ios:5ac2e614a4ec8182b16b7f',
    messagingSenderId: '875378909038',
    projectId: 'fsm-mobile-app-6a2d9',
    storageBucket: 'fsm-mobile-app-6a2d9.appspot.com',
    iosBundleId: 'com.example.fsmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD23AGbp4vVXaRElq8Kn3t0J9fOZPN183g',
    appId: '1:875378909038:web:95d40d737c022ae1b16b7f',
    messagingSenderId: '875378909038',
    projectId: 'fsm-mobile-app-6a2d9',
    authDomain: 'fsm-mobile-app-6a2d9.firebaseapp.com',
    storageBucket: 'fsm-mobile-app-6a2d9.appspot.com',
    measurementId: 'G-D6M2SFC5JC',
  );
}
